version: '3'

services:
  api:
    build: .
    command: 'uvicorn src:app --reload'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest

  test:
    build: .
    command: 'pytest'
    volumes:
      - .:/app
